export const briefExpressCopy = {
    yes: 'oui',
    no: 'non',
    on: 'on',
    off: 'off',
    emptyValue: '—',
    title: '=== Brief express ===',
    labels: {
        project: 'Projet',
        redesign: 'Refonte',
        url: 'URL',
        goals: 'Objectifs',
        other: 'autre',
        target: 'Cible',
        contentReady: 'Contenus prêts',
        advancedForm: 'Formulaire avancé',
        appointment: 'RDV',
        payment: 'Paiement',
        multilingual: 'Multilingue',
        technicalSeo: 'SEO technique',
        accessibility: 'A11y',
        performance: 'Perf',
        integrations: 'Intégrations',
        budget: 'Budget',
        deadline: 'Deadline',
        priority: 'Priorité',
        context: 'Contexte',
        sector: 'Secteur',
        differentiation: 'Différenciation',
        references: 'Références',
        contact: 'Contact',
        firstName: 'Prénom',
        email: 'Email',
        company: 'Entreprise',
        timezone: 'Pays/Fuseau',
        preference: 'Préférence',
    },
    goals: [
        { key: 'leads', text: 'Générer des leads' },
        { key: 'credibilite', text: 'Renforcer la crédibilité' },
        { key: 'vente', text: 'Vendre en ligne' },
        { key: 'recrutement', text: 'Recruter' },
        { key: 'autre', text: 'Autre' },
    ],
    contentsReadyOptions: ['oui', 'non', 'partiel'],
    features: [
        { key: 'blog', text: 'Blog' },
        { key: 'formulaireAvance', text: 'Formulaire avancé' },
        { key: 'rdv', text: 'Prise de RDV' },
        { key: 'paiement', text: 'Paiement en ligne' },
        { key: 'multilingue', text: 'Multilingue' },
        { key: 'seoTechnique', text: 'SEO technique' },
        { key: 'accessibilite', text: 'Accessibilité' },
        { key: 'performances', text: 'Performances' },
    ],
    budgets: [
        { value: '<1000', text: '< 1 000 €' },
        { value: '1000-2000', text: '1 000 – 2 000 €' },
        { value: '2000-4000', text: '2 000 – 4 000 €' },
        { value: '4000-6000', text: '4 000 – 6 000 €' },
        { value: '6000+', text: '6 000 €+' },
    ],
    priorities: ['budget', 'delai', 'qualite'],
    steps: [
        { key: 'projet', label: 'Projet' },
        { key: 'objectifs', label: 'Objectifs & public' },
        { key: 'contenus', label: 'Contenus & fonctionnalités' },
        { key: 'cadrage', label: 'Budget & délai' },
        { key: 'contexte', label: 'Contexte' },
        { key: 'contact', label: 'Coordonnées & RGPD' },
    ],
    errors: {
        firstNameRequired: 'Indique ton prénom.',
        invalidEmail: 'Email invalide.',
        invalidProjectUrl: 'URL invalide. Utilise un lien complet (https://...).',
    },
    submission: {
        visitorFallbackName: 'Visiteur',
        fallbackError: 'Impossible d’envoyer le brief pour l’instant.',
        networkError: 'Erreur réseau. Réessaie dans un instant.',
    },
    attachments: {
        label: 'Pièces jointes (PDF/DOCX/ZIP, max 10 Mo)',
        addFilesCta: 'Ajouter des fichiers',
        selectedCountSuffix: 'fichier(s) sélectionné(s)',
        helper: 'Envoi des fichiers séparément si besoin — ici, on transmet le brief texte. Tu recevras un lien pour partager les pièces jointes.',
    },
} as const;
