export const briefExpressCopy = {
    badge: 'Brief express',
    heading: 'Le minimum utile pour un devis fiable',
    intro: '4–6 minutes, sauvegarde automatique, validation douce. Pas besoin d’écrire un roman —',
    introEmphasis: '10–20 mots suffisent',
    introSuffix: 'quand c’est demandé.',
    restoredDraftNotice: 'Brouillon récupéré depuis cet appareil.',
    progressionAriaLabel: 'Progression du formulaire',
    nav: {
        back: 'Retour',
        next: 'Continuer',
        sending: 'Envoi…',
        submit: 'Envoyer mon brief',
    },
    status: {
        genericError: 'Oups, ça a échoué.',
    },
    cta: {
        intro: 'Tu préfères un échange rapide ? Réserve un créneau — on balise ensemble le périmètre avant chiffrage.',
        bookCall: 'Réserver un appel',
    },
    successModal: {
        closeAriaLabel: 'Fermer la fenêtre',
        title: 'Brief envoyé',
        message: 'Merci ! Je te reviens sous 24–48h ouvrées. Tu peux aussi réserver un créneau si tu préfères.',
        close: 'Fermer',
    },
    options: {
        projectTypes: ['vitrine', 'portfolio', 'ecommerce', 'autre'],
        contactPreferences: ['email', 'appel'],
    },
    fields: {
        projectLegend: 'Projet',
        redesignLabel: 'C’est une refonte',
        currentUrlLabel: 'URL actuelle (si existante)',
        currentUrlPlaceholder: 'https://exemple.com',
        goalsLegend: 'Objectifs & public',
        otherGoalLabel: 'Autre objectif (optionnel)',
        otherGoalPlaceholder: 'Ex. notoriété locale, prise de parole média…',
        targetLabel: 'Cible principale (1 phrase)',
        targetPlaceholder: 'Ex. dirigeants PME en B2B, étudiants…',
        contentLegend: 'Contenus & fonctionnalités',
        contentReadyLabel: 'Contenus prêts ?',
        integrationsLabel: 'Intégrations (Calendly, newsletter, CRM…)',
        integrationsPlaceholder: 'Ex. Calendly, Mailerlite, HubSpot…',
        framingLegend: 'Budget & délai',
        budgetLabel: 'Plage budgétaire',
        deadlineLabel: 'Deadline souhaitée (mois/trim.)',
        priorityLabel: 'Priorité principale',
        contextLegend: 'Contexte',
        sectorLabel: 'Secteur',
        sectorPlaceholder: 'Ex. artisanat, conseil B2B, formation…',
        differentiationLabel: 'Ce qui vous différencie',
        differentiationPlaceholder: 'En 2–3 phrases.',
        referencesLabel: 'Références aimées (1–3 liens)',
        referencesPlaceholder: 'https://site1.com, https://site2.com…',
        contactLegend: 'Coordonnées & RGPD',
        firstNameLabel: 'Prénom *',
        emailLabel: 'Email *',
        companyLabel: 'Entreprise (optionnel)',
        timezoneLabel: 'Pays / fuseau horaire',
        timezonePlaceholder: 'Ex. France (CET), Québec (ET)…',
        contactPreferenceLabel: 'Préférence de contact',
    },
    consent: {
        text: 'J’accepte le traitement de mes données pour répondre à ma demande de devis.',
        helperPrefix: 'Les données sont traitées conformément à la',
        privacyPolicyLabel: 'politique de confidentialité',
    },
    yes: 'oui',
    no: 'non',
    on: 'on',
    off: 'off',
    emptyValue: '—',
    title: '=== Brief express ===',
    labels: {
        project: 'Projet',
        redesign: 'Refonte',
        url: 'URL',
        goals: 'Objectifs',
        other: 'autre',
        target: 'Cible',
        contentReady: 'Contenus prêts',
        advancedForm: 'Formulaire avancé',
        appointment: 'RDV',
        payment: 'Paiement',
        multilingual: 'Multilingue',
        technicalSeo: 'SEO technique',
        accessibility: 'A11y',
        performance: 'Perf',
        integrations: 'Intégrations',
        budget: 'Budget',
        deadline: 'Deadline',
        priority: 'Priorité',
        context: 'Contexte',
        sector: 'Secteur',
        differentiation: 'Différenciation',
        references: 'Références',
        contact: 'Contact',
        firstName: 'Prénom',
        email: 'Email',
        company: 'Entreprise',
        timezone: 'Pays/Fuseau',
        preference: 'Préférence',
    },
    goals: [
        { key: 'leads', text: 'Générer des leads' },
        { key: 'credibilite', text: 'Renforcer la crédibilité' },
        { key: 'vente', text: 'Vendre en ligne' },
        { key: 'recrutement', text: 'Recruter' },
        { key: 'autre', text: 'Autre' },
    ],
    contentsReadyOptions: ['oui', 'non', 'partiel'],
    features: [
        { key: 'blog', text: 'Blog' },
        { key: 'formulaireAvance', text: 'Formulaire avancé' },
        { key: 'rdv', text: 'Prise de RDV' },
        { key: 'paiement', text: 'Paiement en ligne' },
        { key: 'multilingue', text: 'Multilingue' },
        { key: 'seoTechnique', text: 'SEO technique' },
        { key: 'accessibilite', text: 'Accessibilité' },
        { key: 'performances', text: 'Performances' },
    ],
    budgets: [
        { value: '<1000', text: '< 1 000 €' },
        { value: '1000-2000', text: '1 000 – 2 000 €' },
        { value: '2000-4000', text: '2 000 – 4 000 €' },
        { value: '4000-6000', text: '4 000 – 6 000 €' },
        { value: '6000+', text: '6 000 €+' },
    ],
    priorities: ['budget', 'delai', 'qualite'],
    steps: [
        { key: 'projet', label: 'Projet' },
        { key: 'objectifs', label: 'Objectifs & public' },
        { key: 'contenus', label: 'Contenus & fonctionnalités' },
        { key: 'cadrage', label: 'Budget & délai' },
        { key: 'contexte', label: 'Contexte' },
        { key: 'contact', label: 'Coordonnées & RGPD' },
    ],
    errors: {
        firstNameRequired: 'Indique ton prénom.',
        invalidEmail: 'Email invalide.',
        invalidProjectUrl: 'URL invalide. Utilise un lien complet (https://...).',
    },
    submission: {
        visitorFallbackName: 'Visiteur',
        fallbackError: 'Impossible d’envoyer le brief pour l’instant.',
        networkError: 'Erreur réseau. Réessaie dans un instant.',
    },
    attachments: {
        label: 'Pièces jointes (PDF/DOCX/ZIP, max 10 Mo)',
        addFilesCta: 'Ajouter des fichiers',
        selectedCountSuffix: 'fichier(s) sélectionné(s)',
        helper: 'Envoi des fichiers séparément si besoin — ici, on transmet le brief texte. Tu recevras un lien pour partager les pièces jointes.',
    },
} as const;
